version: '3.8'

services:
  app:
    image: ghcr.io/nicodoebele/agent-template-repo:latest
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production